apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen       80;
      server_name  localhost;

      access_log /var/log/nginx/access.log main;
      error_log /var/log/nginx/access.log debug;

      # redirect /api/biosamples requests to the biosamples
      location {{.Values.baseUrl}}{{.Values.apiPrefix}}/biosamples {
          rewrite ^{{.Values.baseUrl}}{{.Values.apiPrefix}}/(.*)$ /$1 break;
          proxy_pass "{{ .Values.biosamplesUrl}}";
      }

      # redirect /api/ena requests to the ena
      location {{.Values.baseUrl}}{{.Values.apiPrefix}}/ena {
          rewrite ^{{.Values.baseUrl}}{{.Values.apiPrefix}}/(.*)$ /$1 break;
          proxy_pass "{{ .Values.enaUrl}}";
      }
      location {{.Values.baseUrl}} {
        alias   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ {{.Values.baseUrl}}/index.html;
      }
      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }

    }
